"""Score DOOM episodes using the LLM rubric.

Takes episodes generated by generate_episodes.py, sends frames to an LLM
for evaluation using the rubric, and outputs rubric-scored episodes.

Usage:
    # Score episodes with rubric (reads LITELLM_API_KEY from env)
    python scripts/score_with_rubric.py \
        --episodes data/episodes_generated.json \
        --output data/episodes_rubric_scored.json \
        --rubric src/doom_multivec/inference/offline_rubric.txt

    # Score with explicit API key (overrides env)
    python scripts/score_with_rubric.py \
        --episodes data/episodes_generated.json \
        --output data/episodes_rubric_scored.json \
        --api-key YOUR_API_KEY

    # Score subset of episodes
    python scripts/score_with_rubric.py \
        --episodes data/episodes_generated.json \
        --output data/episodes_rubric_scored.json \
        --max-episodes 20 \
        --sample-frames 5

    # Use specific model
    python scripts/score_with_rubric.py ... --model gemma-4-27b-it

Environment Variables:
    LITELLM_API_KEY: API key for LLM service (required unless --api-key is provided)

Note:
    Automatically loads .env file from project root if python-dotenv is installed.
"""

import argparse
import json
import os
import sys
import time
from pathlib import Path

# Try to load .env file if python-dotenv is available
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass  # python-dotenv not installed, continue without it

import numpy as np
from tqdm import tqdm

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))


def load_rubric(rubric_path: str) -> str:
    """Load rubric from file."""
    with open(rubric_path) as f:
        return f.read()


def sample_frames(frames: list, num_samples: int) -> list:
    """Sample representative frames from an episode."""
    if len(frames) <= num_samples:
        return list(range(len(frames)))

    # Sample evenly across the episode
    indices = np.linspace(0, len(frames) - 1, num_samples, dtype=int)
    return indices.tolist()


def score_episode_with_llm(
    frames: list,
    rubric: str,
    api_key: str,
    api_url: str,
    model: str,
    sample_frames_count: int = 5,
) -> dict:
    """Score a single episode using the LLM rubric.

    Args:
        frames: List of frame dicts with 'text' (ASCII art).
        rubric: The rubric text to send to LLM.
        api_key: API key for LLM service.
        api_url: API endpoint URL.
        model: Model name to use.
        sample_frames_count: Number of frames to sample for scoring.

    Returns:
        Dict with score and reasoning.
    """
    # Sample frames
    frame_indices = sample_frames(frames, sample_frames_count)
    sampled_frames = [frames[i] for i in frame_indices]

    # Build prompt with rubric + frames
    prompt = f"""{rubric}

Here are {len(sampled_frames)} screenshots from an agent playing DOOM:

"""

    for i, frame in enumerate(sampled_frames):
        prompt += f"\n--- Frame {i+1} ---\n"
        prompt += frame['text']
        prompt += "\n"

    prompt += """

Based on the rubric above, provide a comprehensive score from 0.00 (terrible) to 1.00 (excellent).

Your response MUST be in this exact format:
SCORE: [number between 0.00 and 1.00]
REASONING: [brief explanation of the score]

Be objective and consistent."""

    # Call LLM API
    headers = {
        'Authorization': f'Bearer {api_key}',
        'Content-Type': 'application/json',
    }

    payload = {
        'model': model,
        'messages': [{'role': 'user', 'content': prompt}],
        'max_tokens': 2000,
        'temperature': 0.3,  # Lower for consistency
    }

    try:
        import requests
        response = requests.post(
            api_url,
            headers=headers,
            json=payload,
            timeout=60,
        )
        response.raise_for_status()
        result = response.json()

        message = result['choices'][0]['message']
        content = message.get('content') or message.get('reasoning_content', '')

        if content is None:
            content = ""

        # Parse score
        score = None
        reasoning = ""

        for line in content.split('\n'):
            line = line.strip()
            if line.upper().startswith('SCORE:'):
                try:
                    score_str = line.split(':', 1)[1].strip()
                    # Extract number
                    score = float(score_str.split()[0])
                    score = max(0.0, min(1.0, score))  # Clamp to [0, 1]
                except:
                    pass
            elif line.upper().startswith('REASONING:'):
                reasoning = line.split(':', 1)[1].strip()

        if score is None:
            # Try to extract any number from response
            import re
            numbers = re.findall(r'0\.\d{2}|1\.00', content)
            if numbers:
                score = float(numbers[0])

        if score is None:
            score = 0.5  # Fallback
            reasoning = "Failed to parse score. Response: " + content[:200]

        return {
            'score': score,
            'reasoning': reasoning,
            'frame_indices': frame_indices,
            'api_response': content[:500],  # Truncate for storage
        }

    except Exception as e:
        return {
            'score': 0.5,
            'reasoning': f'API error: {str(e)}',
            'frame_indices': frame_indices,
            'api_response': '',
        }


def main():
    parser = argparse.ArgumentParser(
        description="Score DOOM episodes with LLM rubric"
    )

    # Input/Output
    parser.add_argument(
        '--episodes', '-e',
        required=True,
        help='Path to episodes JSON file',
    )
    parser.add_argument(
        '--output', '-o',
        required=True,
        help='Output path for scored episodes',
    )
    parser.add_argument(
        '--rubric',
        default='src/doom_multivec/inference/offline_rubric.txt',
        help='Path to rubric text file',
    )

    # LLM API
    parser.add_argument(
        '--api-key',
        default=os.environ.get('LITELLM_API_KEY'),
        help='API key (overrides LITELLM_API_KEY env var)',
    )
    parser.add_argument(
        '--api-url',
        default='https://tritonai-api.ucsd.edu/v1/chat/completions',
        help='API endpoint URL',
    )
    parser.add_argument(
        '--model',
        default='api-gemma-4-26b',
        help='Model to use for scoring',
    )

    # Scoring options
    parser.add_argument(
        '--max-episodes',
        type=int,
        default=None,
        help='Maximum episodes to score (for testing)',
    )
    parser.add_argument(
        '--sample-frames',
        type=int,
        default=5,
        help='Number of frames to sample per episode',
    )
    parser.add_argument(
        '--retry-failed',
        action='store_true',
        help='Retry failed API calls',
    )
    parser.add_argument(
        '--delay',
        type=float,
        default=1.0,
        help='Delay between API calls (seconds)',
    )

    # Caching
    parser.add_argument(
        '--resume',
        action='store_true',
        help='Resume from partial output file',
    )

    args = parser.parse_args()

    print("=" * 60)
    print("DOOM MultiVec - Rubric Scoring")
    print("=" * 60)

    # Check API key
    if not args.api_key:
        print("\nError: API key required!")
        print("Set LITELLM_API_KEY environment variable or provide --api-key.")
        return 1

    # Load rubric
    print(f"\nLoading rubric from {args.rubric}...")
    rubric = load_rubric(args.rubric)
    print(f"  Rubric length: {len(rubric)} chars")

    # Load episodes
    print(f"Loading episodes from {args.episodes}...")
    with open(args.episodes) as f:
        data = json.load(f)

    episodes = data.get('episodes', [])
    metadata = data.get('metadata', {})
    print(f"  Loaded {len(episodes)} episodes")

    if args.max_episodes:
        episodes = episodes[:args.max_episodes]
        print(f"  Scoring first {len(episodes)} episodes")

    # Load existing scores if resuming
    existing_scores = {}
    if args.resume and os.path.exists(args.output):
        print(f"Loading existing scores from {args.output}...")
        with open(args.output) as f:
            existing_data = json.load(f)
        for ep in existing_data.get('episodes', []):
            if 'rubric_score' in ep:
                existing_scores[id(ep)] = ep['rubric_score']
        print(f"  Found {len(existing_scores)} existing scores")

    # Score episodes
    print(f"\nScoring {len(episodes)} episodes...")
    print(f"  Model: {args.model}")
    print(f"  Frames per episode: {args.sample_frames}")
    print(f"  Delay between calls: {args.delay}s")
    print()

    scored_episodes = []
    scores = []

    for i, episode in enumerate(tqdm(episodes, desc="Scoring")):
        # Check if already scored
        ep_id = id(episode)
        if ep_id in existing_scores:
            episode['rubric_score'] = existing_scores[ep_id]
            episode['rubric_cached'] = True
            scored_episodes.append(episode)
            scores.append(existing_scores[ep_id])
            continue

        # Score with LLM
        result = score_episode_with_llm(
            episode['frames'],
            rubric,
            args.api_key,
            args.api_url,
            args.model,
            args.sample_frames,
        )

        episode['rubric_score'] = result['score']
        episode['rubric_reasoning'] = result['reasoning']
        episode['rubric_frame_indices'] = result['frame_indices']
        episode['rubric_api_response'] = result['api_response']

        scored_episodes.append(episode)
        scores.append(result['score'])

        # Progress
        if (i + 1) % 10 == 0:
            avg_score = sum(scores) / len(scores)
            print(f"  Progress: {i+1}/{len(episodes)}, avg_score={avg_score:.3f}")

        # Delay to avoid rate limits
        time.sleep(args.delay)

    # Statistics
    print(f"\n{'=' * 60}")
    print("Scoring complete!")
    print(f"{'=' * 60}")
    print(f"Episodes scored: {len(scored_episodes)}")
    print(f"Score distribution:")
    print(f"  Min: {min(scores):.3f}")
    print(f"  Max: {max(scores):.3f}")
    print(f"  Mean: {sum(scores)/len(scores):.3f}")
    print(f"  Median: {sorted(scores)[len(scores)//2]:.3f}")

    # Bin distribution
    low = sum(1 for s in scores if s < 0.33)
    mid = sum(1 for s in scores if 0.33 <= s < 0.67)
    high = sum(1 for s in scores if s >= 0.67)
    print(f"\nScore bins:")
    print(f"  Low (< 0.33):    {low} ({low/len(scores)*100:.1f}%)")
    print(f"  Mid (0.33-0.67): {mid} ({mid/len(scores)*100:.1f}%)")
    print(f"  High (> 0.67):   {high} ({high/len(scores)*100:.1f}%)")

    # Save output
    os.makedirs(os.path.dirname(args.output) or '.', exist_ok=True)

    output_data = {
        'episodes': scored_episodes,
        'metadata': {
            **metadata,
            'rubric_file': args.rubric,
            'scoring_model': args.model,
            'sample_frames': args.sample_frames,
            'num_scored': len(scored_episodes),
            'score_statistics': {
                'min': min(scores),
                'max': max(scores),
                'mean': sum(scores)/len(scores),
                'median': sorted(scores)[len(scores)//2],
            }
        }
    }

    with open(args.output, 'w') as f:
        json.dump(output_data, f, indent=2)

    print(f"\nSaved to: {args.output}")
    print(f"File size: {os.path.getsize(args.output) / 1024 / 1024:.1f} MB")

    print("\n" + "=" * 60)
    print("Next step: Prepare DPO data")
    print(f"  python scripts/prepare_dpo_data.py \\")
    print(f"      --episodes {args.output} \\")
    print(f"      --output data/dpo_preferences.json")
    print("=" * 60)

    return 0


if __name__ == '__main__':
    sys.exit(main())
